[env:bluepill_f103c8]
platform  = ststm32
board     = bluepill_f103c8
framework = stm32cube

build_flags =
    -Iinclude
    -I/home/codespace/.platformio/packages/framework-stm32cubef1/Middlewares/Third_Party/FreeRTOS/Source/include
    -I/home/codespace/.platformio/packages/framework-stm32cubef1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3
    -DSTM32F103xB
    -DUSE_HAL_DRIVER
    -DHSE_VALUE=8000000UL
    -O2

monitor_speed = 115200
