[env:bluepill_f103c8]
platform  = ststm32
board     = bluepill_f103c8
framework = stm32cube

build_flags =
    -Iinclude
    -I.pio/libdeps/bluepill_f103c8/FreeRTOS-Kernel/include
    -I.pio/libdeps/bluepill_f103c8/FreeRTOS-Kernel/portable/GCC/ARM_CM3
    -DSTM32F103xB
    -DUSE_HAL_DRIVER
    -DHSE_VALUE=8000000UL
    -O2

lib_deps =
    https://github.com/FreeRTOS/FreeRTOS-Kernel.git#V11.1.0

lib_ldf_mode = chain

build_src_filter =
    +<*>

lib_compat_mode = off

extra_scripts = pre:scripts/prune_freertos.py
