[env:bluepill_f103c8]
platform  = ststm32
board     = bluepill_f103c8
framework = stm32cube

build_flags =
    -Iinclude
    -DSTM32F103xB
    -DUSE_HAL_DRIVER
    -DHSE_VALUE=8000000UL
    -O2

lib_deps =
    https://github.com/FreeRTOS/FreeRTOS-Kernel.git#V11.1.0

monitor_speed = 115200
